### ISSUE TITLE
Let's collaborate all together ?

### ISSUE THREAD

**Issue by FrancescoBorzi** [xDevICCI/Azerothcore---core-Chile#2]
Hi @xDevICCI thanks for using AzerothCore!. Would you like to open PRs to the main repo at https://github.com/azerothcore/azerothcore-wotlk ? So we can unite our forces and make a better WoW experience.

**Comment by xDevICCI** [comment]
Perfect !

**Comment by xDevICCI** [comment]
@FrancescoBorzi go

**Comment by masterking32** [comment]
Thank you @xDevICCI

**Comment by FrancescoBorzi** [comment]
[How to create a Pull Request](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request)

@xDevICCI compa, únete a nosotros en la chat: https://discordapp.com/channels/217589275766685707/284406375495368704
